version: "3.9"

services:
  astrocorner-db:
    container_name: astrocorner-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=astrocorner
    ports:
      - target: 3306
        published: 3307

  maildev:
    container_name: astrocorner-maildev
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "4080:1080"
      - "4025:1025"